### ISSUE TITLE
Fehler nach Installation in Contao 3.5

### ISSUE THREAD

**Issue by abroess** [kirsten-roschanski/contao-extended-dca#3]
Nach der Installation unter Contao 3.5 ist die Contao Installation unbrauchbar. Es erscheint nur noch die Fehlermeldung:

> The module dependencies could not be resolved.
> Array
> (
>    [kirsten-roschanski-extended-dca] => Array
>        (
>            [0] => core
>            [1] => news
>        )
> 
> )

**Comment by katgirl** [comment]
Ich habe das auch unter 3.5 laufen, ohne Probleme, hast du die News raus geworfen?

**Comment by katgirl** [comment]
Das ist die Abhängigkeit zu News und dem Core

**Comment by abroess** [comment]
Ja, die ist nicht aktiv. Braucht man ja nicht überall, sondern nur bei Bedarf.

**Comment by katgirl** [comment]
nimm mal bitte den develop-Zweig

**Comment by katgirl** [comment]
bzw. lösche in https://github.com/kirsten-roschanski/contao-extended-dca/commit/c4cf19a00367528d9ce61e02d16413512d69cc95

**Comment by abroess** [comment]
So einfach mache ich es Dir nicht meine Liebe:

> Fatal error: Class 'tl_news' not found in /var/www/virtual/elch02/distri3.werkstest.de/system/modules/kirsten-roschanski-extended-dca/dca/tl_news.php on line 25

**Comment by katgirl** [comment]
Bitte statt dem bundle nun nur https://packagist.org/packages/kirsten-roschanski/contao-extended-dca verwenden.

**Comment by abroess** [comment]
Habe ich gemacht. Es funktioniert nur, wenn die News nicht deaktiviert sind. Wir auch nicht bei der Installation abgefragt bzw. richtig geprüft. Daher läuft man aufgrund der fehlenden Tabellen immer wieder in den Fehler.

**Comment by katgirl** [comment]
Core --> https://packagist.org/packages/kirsten-roschanski/contao-extended-core-dca
News --> https://packagist.org/packages/kirsten-roschanski/contao-extended-news-dca

Bundle --> https://packagist.org/packages/kirsten-roschanski/contao-extended-dca
ich habe es in allen Varianten versucht und konnte keinen Fehler feststellen. Hast du in der Installation vielleicht noch was im Cache oder der Ordner in system/modules wurde nicht gelöscht?

**Comment by abroess** [comment]
Ha. lustig. nach dem Update auf 3.5 wurde wohl auch die Erweiterung aktualisiert und funktioniert jetzt sauber. Danke fein für die Aufteilung.
